spring:
  application:
    name: user-service
  
  profiles:
    active: local  # Use local profile by default
  
  datasource:
    url: ${USER_DB_URL:jdbc:postgresql://localhost:5432/user_db}
    username: ${USER_DB_USERNAME:user_admin}
    password: ${USER_DB_PASSWORD:user_pass_123}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update  # Creates tables automatically
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081

logging:
  level:
    com.transport.user: DEBUG