spring:
  application:
    name: ticketing-service
  
  datasource:
    url: ${TICKETING_DB_URL}
    username: ${TICKETING_DB_USERNAME}
    password: ${TICKETING_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver